spring:
  datasource:
     url: jdbc:mysql://localhost:3306/paymentdb
     username: root
     password: root
  jpa:
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  application:
    name: PAYMENT-SERVICE
server:
  port: 8081
eureka:
 instance:
    hostname: localhost
 client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
okta:
  oauth2:
    issuer: https://dev-86597411.okta.com/oauth2/default
    audience: api://default
    